// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmos/farming/v1beta1/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/codec/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "github.com/regen-network/cosmos-proto"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the farming module's genesis state.
type GenesisState struct {
	// params defines all the parameters for the farming module
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// plan_records defines the plan records used for genesis state
	PlanRecords []PlanRecord `protobuf:"bytes,2,rep,name=plan_records,json=planRecords,proto3" json:"plan_records" yaml:"plan_records"`
	// stakings defines the staking records used for genesis state
	Stakings []Staking `protobuf:"bytes,3,rep,name=stakings,proto3" json:"stakings"`
	// rewards defines the reward records used for genesis state
	Rewards []Reward `protobuf:"bytes,4,rep,name=rewards,proto3" json:"rewards"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab5716c14f48023, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

// PlanRecord is used for import/export via genesis json.
type PlanRecord struct {
	// plan specifies the plan interface; it can be FixedAmountPlan or RatioPlan
	Plan types.Any `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan"`
	// last_epoch_time specifies the last distributed epoch time of the plan
	LastEpochTime time.Time `protobuf:"bytes,2,opt,name=last_epoch_time,json=lastEpochTime,proto3,stdtime" json:"last_epoch_time" yaml:"last_epoch_time"`
	// farming_pool_coins specifies balance of the farming pool for the plan
	// this param is needed for import/export validation
	FarmingPoolCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=farming_pool_coins,json=farmingPoolCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"farming_pool_coins" yaml:"farming_pool_coins"`
	// distribution_pool_coins specifies balance of the distribution pool to be distributed in the plan
	// this param is needed for import/export validation
	DistributionPoolCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=distribution_pool_coins,json=distributionPoolCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"distribution_pool_coins" yaml:"distribution_pool_coins"`
	// staking_reserve_coins specifies balance of the staking reserve pool staked in the plan
	// this param is needed for import/export validation
	StakingReserveCoins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=staking_reserve_coins,json=stakingReserveCoins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"staking_reserve_coins" yaml:"staking_reserve_coins"`
}

func (m *PlanRecord) Reset()         { *m = PlanRecord{} }
func (m *PlanRecord) String() string { return proto.CompactTextString(m) }
func (*PlanRecord) ProtoMessage()    {}
func (*PlanRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ab5716c14f48023, []int{1}
}
func (m *PlanRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlanRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlanRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlanRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlanRecord.Merge(m, src)
}
func (m *PlanRecord) XXX_Size() int {
	return m.Size()
}
func (m *PlanRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PlanRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PlanRecord proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenesisState)(nil), "cosmos.farming.v1beta1.GenesisState")
	proto.RegisterType((*PlanRecord)(nil), "cosmos.farming.v1beta1.PlanRecord")
}

func init() {
	proto.RegisterFile("cosmos/farming/v1beta1/genesis.proto", fileDescriptor_5ab5716c14f48023)
}

var fileDescriptor_5ab5716c14f48023 = []byte{
	// 581 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xed, 0x36, 0x2d, 0xd5, 0xa5, 0x08, 0xe4, 0xfe, 0x20, 0x09, 0xc8, 0xae, 0x2c, 0x86,
	0x0c, 0x60, 0xab, 0x65, 0xab, 0x10, 0x52, 0x83, 0x10, 0x12, 0x12, 0x52, 0xe4, 0x32, 0xb1, 0x58,
	0xe7, 0xe4, 0xe2, 0x5a, 0xb5, 0xef, 0x2c, 0xdf, 0xa5, 0x90, 0xff, 0x80, 0xb1, 0x2c, 0xac, 0x74,
	0x41, 0x42, 0xfc, 0x0f, 0xec, 0x1d, 0x3b, 0x32, 0xb5, 0x28, 0x59, 0x98, 0xf9, 0x0b, 0xd0, 0xdd,
	0x3d, 0x27, 0x51, 0x5b, 0x53, 0x75, 0x8a, 0x75, 0xfe, 0xbe, 0xcf, 0x7d, 0xde, 0xf3, 0x53, 0xd0,
	0xe3, 0x1e, 0xe3, 0x19, 0xe3, 0xfe, 0x00, 0x17, 0x59, 0x42, 0x63, 0xff, 0x68, 0x3b, 0x22, 0x02,
	0x6f, 0xfb, 0x31, 0xa1, 0x84, 0x27, 0xdc, 0xcb, 0x0b, 0x26, 0x98, 0xb5, 0xa9, 0x53, 0x1e, 0xa4,
	0x3c, 0x48, 0xb5, 0x9a, 0x31, 0x63, 0x71, 0x4a, 0x7c, 0x95, 0x8a, 0x86, 0x03, 0x1f, 0xd3, 0x91,
	0x2e, 0x69, 0xad, 0xc7, 0x2c, 0x66, 0xea, 0xd1, 0x97, 0x4f, 0x70, 0xda, 0xd4, 0xa0, 0x50, 0xbf,
	0x00, 0xaa, 0x7e, 0x65, 0x83, 0x49, 0x84, 0x39, 0x99, 0x6a, 0xf4, 0x58, 0x42, 0xe1, 0x7d, 0x95,
	0x69, 0xe9, 0xa4, 0x53, 0xce, 0x65, 0x23, 0x91, 0x64, 0x84, 0x0b, 0x9c, 0xe5, 0x3a, 0xe0, 0xfe,
	0x5c, 0x40, 0xab, 0xaf, 0x75, 0x73, 0xfb, 0x02, 0x0b, 0x62, 0x3d, 0x47, 0xcb, 0x39, 0x2e, 0x70,
	0xc6, 0x1b, 0xe6, 0x96, 0xd9, 0xae, 0xef, 0xd8, 0xde, 0xf5, 0xcd, 0x7a, 0x5d, 0x95, 0xea, 0xd4,
	0x4e, 0xcf, 0x1d, 0x23, 0x80, 0x1a, 0x2b, 0x42, 0xab, 0x79, 0x8a, 0x69, 0x58, 0x90, 0x1e, 0x2b,
	0xfa, 0xbc, 0xb1, 0xb0, 0xb5, 0xd8, 0xae, 0xef, 0xb8, 0x95, 0x8c, 0x14, 0xd3, 0x40, 0x45, 0x3b,
	0x0f, 0x25, 0xe7, 0xef, 0xb9, 0xb3, 0x36, 0xc2, 0x59, 0xba, 0xeb, 0xce, 0x53, 0xdc, 0xa0, 0x9e,
	0x4f, 0x83, 0xdc, 0xda, 0x43, 0x2b, 0x5c, 0xe0, 0xc3, 0x84, 0xc6, 0xbc, 0xb1, 0xa8, 0xf8, 0x4e,
	0x15, 0x7f, 0x5f, 0xe7, 0x40, 0x72, 0x5a, 0x66, 0xbd, 0x40, 0x77, 0x0a, 0xf2, 0x01, 0x4b, 0xc3,
	0x9a, 0x22, 0x54, 0x76, 0x19, 0xa8, 0x18, 0x00, 0xca, 0xa2, 0xdd, 0x95, 0x4f, 0x27, 0x8e, 0xf1,
	0xe7, 0xc4, 0x31, 0xdc, 0xcf, 0x4b, 0x08, 0xcd, 0xba, 0xb0, 0x3c, 0x54, 0x93, 0xaa, 0x30, 0xbb,
	0x75, 0x4f, 0x8f, 0xdf, 0x2b, 0xc7, 0xef, 0xed, 0xd1, 0x11, 0xb0, 0x54, 0xce, 0x1a, 0xa0, 0x7b,
	0x29, 0xe6, 0x22, 0x24, 0x39, 0xeb, 0x1d, 0x84, 0xf2, 0xe3, 0x34, 0x16, 0x54, 0x69, 0xeb, 0x4a,
	0xe9, 0xbb, 0xf2, 0xcb, 0x75, 0x5c, 0x18, 0xd5, 0xa6, 0x1e, 0xd5, 0x25, 0x80, 0x7b, 0x7c, 0xe1,
	0x98, 0xc1, 0x5d, 0x79, 0xfa, 0x4a, 0x1e, 0xca, 0x3a, 0xeb, 0x8b, 0x89, 0x2c, 0x68, 0x2d, 0xcc,
	0x19, 0x4b, 0x43, 0xb9, 0x49, 0xe5, 0xf8, 0x9a, 0x65, 0xf3, 0x72, 0xd7, 0xa6, 0x9d, 0xbf, 0x64,
	0x09, 0xed, 0xbc, 0x85, 0xab, 0x9a, 0xfa, 0xaa, 0xab, 0x08, 0xf7, 0xc7, 0x85, 0xd3, 0x8e, 0x13,
	0x71, 0x30, 0x8c, 0xbc, 0x1e, 0xcb, 0x60, 0x87, 0xe1, 0xe7, 0x29, 0xef, 0x1f, 0xfa, 0x62, 0x94,
	0x13, 0xae, 0x68, 0x3c, 0xb8, 0x0f, 0x80, 0x2e, 0x63, 0xa9, 0x3a, 0xb1, 0xbe, 0x99, 0xe8, 0x41,
	0x3f, 0xe1, 0xa2, 0x48, 0xa2, 0xa1, 0x48, 0x18, 0x9d, 0xb7, 0xab, 0xdd, 0x64, 0x17, 0x80, 0x9d,
	0xad, 0xed, 0x2a, 0x38, 0xb7, 0x53, 0xdc, 0x98, 0xa7, 0xcc, 0x3c, 0xbf, 0x9a, 0x68, 0x03, 0xd6,
	0x27, 0x2c, 0x08, 0x27, 0xc5, 0x11, 0x01, 0xcb, 0xa5, 0x9b, 0x2c, 0xbb, 0x60, 0xf9, 0x48, 0x5b,
	0x5e, 0x4b, 0xb9, 0x9d, 0xe3, 0x1a, 0x30, 0x02, 0x8d, 0x50, 0x87, 0xb3, 0x9d, 0xec, 0xbc, 0xf9,
	0x3e, 0xb6, 0xcd, 0xd3, 0xb1, 0x6d, 0x9e, 0x8d, 0x6d, 0xf3, 0xf7, 0xd8, 0x36, 0x8f, 0x27, 0xb6,
	0x71, 0x36, 0xb1, 0x8d, 0x5f, 0x13, 0xdb, 0x78, 0xff, 0xe4, 0xbf, 0xd7, 0x7c, 0x9c, 0xfe, 0xa1,
	0xa8, 0x0b, 0xa3, 0x65, 0xb5, 0x7f, 0xcf, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0xaf, 0x0e, 0x47,
	0x26, 0x19, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Rewards) > 0 {
		for iNdEx := len(m.Rewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Rewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Stakings) > 0 {
		for iNdEx := len(m.Stakings) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stakings[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.PlanRecords) > 0 {
		for iNdEx := len(m.PlanRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PlanRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PlanRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlanRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlanRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StakingReserveCoins) > 0 {
		for iNdEx := len(m.StakingReserveCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakingReserveCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.DistributionPoolCoins) > 0 {
		for iNdEx := len(m.DistributionPoolCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DistributionPoolCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.FarmingPoolCoins) > 0 {
		for iNdEx := len(m.FarmingPoolCoins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FarmingPoolCoins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.LastEpochTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.LastEpochTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintGenesis(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Plan.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PlanRecords) > 0 {
		for _, e := range m.PlanRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Stakings) > 0 {
		for _, e := range m.Stakings {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Rewards) > 0 {
		for _, e := range m.Rewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *PlanRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Plan.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.LastEpochTime)
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.FarmingPoolCoins) > 0 {
		for _, e := range m.FarmingPoolCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.DistributionPoolCoins) > 0 {
		for _, e := range m.DistributionPoolCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakingReserveCoins) > 0 {
		for _, e := range m.StakingReserveCoins {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PlanRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PlanRecords = append(m.PlanRecords, PlanRecord{})
			if err := m.PlanRecords[len(m.PlanRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stakings", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stakings = append(m.Stakings, Staking{})
			if err := m.Stakings[len(m.Stakings)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Rewards = append(m.Rewards, Reward{})
			if err := m.Rewards[len(m.Rewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PlanRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlanRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlanRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Plan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Plan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastEpochTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.LastEpochTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FarmingPoolCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FarmingPoolCoins = append(m.FarmingPoolCoins, types1.Coin{})
			if err := m.FarmingPoolCoins[len(m.FarmingPoolCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributionPoolCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistributionPoolCoins = append(m.DistributionPoolCoins, types1.Coin{})
			if err := m.DistributionPoolCoins[len(m.DistributionPoolCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakingReserveCoins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakingReserveCoins = append(m.StakingReserveCoins, types1.Coin{})
			if err := m.StakingReserveCoins[len(m.StakingReserveCoins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
